name: Synchronize the example with the template
on:
  push:
    branches: [ main ]

jobs:
  synchronize_example:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: PROJ_NAME
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo generate
        uses: cargo-generate/cargo-generate-action@v0.18.4
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: template
          template_values_file: .github/workflows/template_values.toml

      - name: Checkout old example
        uses: actions/checkout@v3
        with:
          repository: rust-github/PROJ_NAME
          path: old_example
          ssh-key: ${{ secrets.GH_EXAMPLE_DEPLOY_SECRET }}

      - name: move sources, mit license and Cargo.toml from old to new example
        run: |
          echo "pwd:"
          pwd
          echo "ls -al:"
          ls -al
          rm PROJ_NAME/src/main.rs
          rm PROJ_NAME/Cargo.toml
          rm PROJ_NAME/LICENSE-MIT
          cp old_example/src/* PROJ_NAME/src/
          cp old_example/Cargo.toml PROJ_NAME/Cargo.toml
          cp old_example/LICENSE-MIT PROJ_NAME/LICENSE-MIT
      - name: update example
        run: |
          mkdir old_sources
          mv old_example/src/* old_sources
          cd old_example
          rm -rf * .gitignore .github/
          echo "ls ../PROJ_NAME:"
          ls ../PROJ_NAME
          echo "ls ../PROJ_NAME/src:"
          ls ../PROJ_NAME/src
          mv ../PROJ_NAME/* ../PROJ_NAME/.github ../PROJ_NAME/.gitignore .
          echo "ls -al:"
          ls -al
          rm src/*
          mv ../old_sources/* src
      - name: commit example
        run: |
          cd old_example
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "automatic update" -m "from $GITHUB_REPOSITORY@$GITHUB_SHA"
            git push
          else
            echo "nothing to commit";
          fi